<div class="image">

  <img style="float: right;" src="https://pku.org.uk/head.png" width="45%" align="right">
      <h4>
          <p style="font-size:25pt">UK19B307 AI Analytics</p>
          <p style="font-size:15pt">Additional Quiz</p>
      </h4>
<h5>
    <p> Peking University</p>
    <p> Demonstrable Labs</p>
</h5>
</div>

### Please doule click this block and enter your name / ID:

- Name: Zhang Ziqing
- ID: 1901212856

In [50]:
import numpy as np
import pandas as pd

<div class="alert alert-warning">
<b>QUESTION 1:</b> 
    
Please print the following string using **ONE LINE** of code:
    
```
Dear Alice,

Eve's cat has been found in hotel "Kitty".

Sincerely,
Bob
```

</div>

In [4]:
print('Dear Alice,\nEve\'s cat has been found in hotel "Kitty".\nSincerely,\nBob')

Dear Alice,
Eve's cat has been found in hotel "Kitty".
Sincerely,
Bob


<div class="alert alert-warning">
<b>QUESTION 2:</b> 
    
1, Define a string: `names = 'Olivia; Amelia; Isla; Ava; Grace'`
  
2, Split the names in the string and turn it into a list. Print the list, the expected output is:
   
`['Olivia', 'Amelia', 'Isla', 'Ava', 'Grace']`
</div>

In [5]:
names = 'Olivia; Amelia; Isla; Ava; Grace'
print('Olivia; Amelia; Isla; Ava; Grace'.split(';'))

['Olivia', ' Amelia', ' Isla', ' Ava', ' Grace']


<div class="alert alert-warning">
<b>QUESTION 3:</b>

One of the activation functions used in neural network is SQNL. When SQNL is used, the following equation is applied to the input signal: 
    
$f(x) = \left\{\begin{matrix} 1 & :x>2.0\\ x-\frac{x^{2}}{4}&:0\leq x\leq 2.0 \\ x+\frac{x^{2}}{4}&:-2.0\leq x<0 \\ -1 & :x<-2.0 \end{matrix}\right.$
<br>    
Write a function called <code>SQNL</code> which takes a number as the argument. The function would **return** the result of applying the activation function.

</div>

In [10]:
def SQNL(x):
    if x >2.0:
        return 1
    elif 0<=x<=2.0:
        return x-x**2/4
    elif 2.0<=𝑥<0:
         return x+x**2/4
    elif x<2.0:
        return -1
print(SQNL(3))
        

1


<div class="alert alert-warning">
<b>QUESTION 4:</b>
    
Please fill the gaps in the code below so that the output of it would be `The percetage of the shares Jake holds is 9.68%.`(**DO NOT** miss the period at the end of the sentence).
    
```python
Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}
print('________________'.format(_________))
```
</div>

In [11]:
Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}
print('The percetage of the shares Jake holds is'.format()

The percetage of the shares Jake holds is


<div class="alert alert-warning">
<b>QUESTION 5:</b>
    
1, Define a dictionary: `Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}`

2, Using **ONE LINE** of code, create a list called `share_values` which contains all the values in the dictionary `Shares`.
    
3, Print `share_values`, the expected output is: `[2359, 4032, 5538, 3200, 7239, 2007]`
</div>

In [16]:
Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}
share_values = print(Shares.values())

dict_values([2359, 4032, 5538, 3200, 7239, 2007])


<div class="alert alert-warning">
<b>QUESTION 6:</b>
    
Please fill the gaps in the code below so that the output of it would be `[103, 105, 107, 109]`
    
```python
nums = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
print(nums[______])
```
</div>

In [22]:
nums = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
print(nums[2:9:2])

[103, 105, 107, 109]


<div class="alert alert-warning">
<b>QUESTION 7:</b>
    
1, Define a list: `scores = [40,69,42,68,90,73,77,22,10,63,81,58,80,55,66,39,74]`

2, Write **ONE LINE** of code to print the number of elements (in the list) that are larger than 50 and smaller than 70. The expected output is : `6`
    
<br>  
    <b>DO NOT</b> write print(6)
</div>

In [88]:
scores = [40,69,42,68,90,73,77,22,10,63,81,58,80,55,66,39,74]
print(scores.count(x for x in scores if 50 < x < 70))

AttributeError: 'generator' object has no attribute 'count'

<div class="alert alert-warning">
<b>QUESTION 8:</b>
    
Create a list which contains numbers from 500 to 0, with an interval of 50. The list should start with 500 and end with 0.
    
Print the list, the expected output is: `[500, 450, 400, 350, 300, 250, 200, 150, 100, 50, 0]`
</div>

In [37]:
print(list(range(500,-1,-50)))

[500, 450, 400, 350, 300, 250, 200, 150, 100, 50, 0]


<div class="alert alert-warning">
<b>QUESTION 9: </b> 

1, Define a dictionary: `captials = {'China':'Peking', 'USA':'Washington', 'Russia':'Moscow', 'UK':'London', 'France':'Paris'}`

2, Change the value `Peking` to `Beijing`. Print the dictionary, the expected output is: `{'China': 'Beijing', 'USA': 'Washington', 'Russia': 'Moscow', 'UK': 'London', 'France': 'Paris'}`.

In [40]:
captials = {'China':'Peking', 'USA':'Washington', 'Russia':'Moscow', 'UK':'London', 'France':'Paris'}
captials.update({"China":'Beijing'})
print(captials)

{'China': 'Beijing', 'USA': 'Washington', 'Russia': 'Moscow', 'UK': 'London', 'France': 'Paris'}


<div class="alert alert-warning">
<b>QUESTION 10:</b>
    
1, Define a list: `list_abc = ['Joe', 'Kik', 'Olo', 'Seb', Jokoj, 'MadAm', 'Yolo']`
    
2, Create a for loop that iterates through `list_abc` and prints `Not a palindrome!` if the element is not a palindrome and prints `Palindrome!` if the element is a palindrome.
    
Note: Palindrome is a word that reads the same backwords and forwards, such as *'Kik'*, *'MadAm'* or *'kayak'*.

3, The expected output is:
```
Not a palindrome!
Palindrome!
Palindrome!
Not a palindrome!
Palindrome!
Palindrome!
Not a palindrome!```
</div>

In [48]:
list_abc = ['Joe', 'Kik', 'Olo', 'Seb', 'Jokoj', 'MadAm', 'Yolo']
def isPalindrome(str): 
    for i in list_abc(0, len(str)/2):  
        if str[i] != str[len(str)-i-1]: 
            return  False
    return True

for i in list_abc:
    s = isPalindrome(i): 
        print('Palindrome!')

SyntaxError: invalid syntax (<ipython-input-48-30ea60320d37>, line 9)

<div class="alert alert-warning">
<b>QUESTION 11: </b> 

1, Define two arrays:
    
```python
arr_1 = np.array([[1, 3, 5], [7, 9, 11]])
arr_2 = np.array([[2, 4, 6], [8, 10, 12]])
```
    
2, Add `arr_1` and `arr_2` element by element. Print the result, the expected output is:
    
```
[[ 3  7 11]
 [15 19 23]]```

</div>

In [51]:
arr_1 = np.array([[1, 3, 5], [7, 9, 11]])
arr_2 = np.array([[2, 4, 6], [8, 10, 12]])
arr_1+arr_2

array([[ 3,  7, 11],
       [15, 19, 23]])

<div class="alert alert-warning">
<b>QUESTION 12:</b>
    
1, Define an array: `arr = np.arange(15).reshape(3, 5)`

2, Print the array below by indexing `arr`.

```    
[[ 6  7]
 [11 12]]```

</div>

In [54]:
arr = np.arange(15).reshape(3, 5)
arr
print(arr[1:3, 1:3])

[[ 6  7]
 [11 12]]


<div class="alert alert-warning">
<b>QUESTION 13:</b>
    
1, Define an array: `arr = np.array([[-1, 9, 10], [3, -2, 9], [6, 2, 2]])`

2, Replace the negative numbers in `arr` with 0. Print the new array, the expected output is:

```    
[[ 0  9 10]
 [ 3  0  9]
 [ 6  2  2]]```

</div>

In [55]:
arr = np.array([[-1, 9, 10], [3, -2, 9], [6, 2, 2]])
arr[arr<0] = 0
print(arr)

[[ 0  9 10]
 [ 3  0  9]
 [ 6  2  2]]


<div class="alert alert-warning">
<b>QUESTION 14:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Get the data from the last column as a one-dimensional array. Print the array, the expected output is:
```
[ 2  5  8 11 14 17 20]```

</div>

In [59]:
arr = np.arange(21).reshape(7,3)
arr
arr_1 = np.array(arr[:,2])
arr_1

array([ 2,  5,  8, 11, 14, 17, 20])

<div class="alert alert-warning">
<b>QUESTION 15:</b>
    
1, Define an array: 
```python
arr = np.array([[11,  9,  5],
                [ 2,  5,  8],
                [ 7,  5,  2],
                [10, 13,  1]])
```

2, Sort the values in each row of `arr` in ascending order. Print the new array, the expected output is:
```
[[ 5  9 11]
 [ 2  5  8]
 [ 2  5  7]
 [ 1 10 13]]```

</div>

In [60]:
arr = np.array([[11,  9,  5],
                [ 2,  5,  8],
                [ 7,  5,  2],
                [10, 13,  1]])
arr.sort()
print(arr)

[[ 5  9 11]
 [ 2  5  8]
 [ 2  5  7]
 [ 1 10 13]]


<div class="alert alert-warning">
<b>QUESTION 16:</b>

1, Define a DataFrame called `exam_attempts`:
```python
exam_attempts  = pd.DataFrame({'NAME': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                               'ATTEMPTS': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]})
```        
   
2, Convert the column names from upper case to lower case. Display the DataFrame `exam_attempts`. The expected output would be:

<img src="//i.imgur.com/GtpPSpq.png" height="14%" width="14%">
</div>

In [69]:
exam_attempts  = pd.DataFrame({'NAME': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                               'ATTEMPTS': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]})
exam_attempts.columns = map(str.lower,exam_attempts.columns)
exam_attempts

name  attempts
0  Anastasia         1
1       Andy         3
2  Katherine         2
3      Helen         3
4      Emily         2
5    Michael         3
6    Matthew         1
7      Maria         1
8      Kevin         2
9      Jonas         1

<div class="alert alert-warning">
<b>QUESTION 17:</b>

1, Add `1` to each value in column `attempts` from DataFrame `exam_attempts`.

2, Display the **updated** DataFrame `exam_attempts`, the expected output would be:
    
<img src="//i.imgur.com/RgkRw5C.png" height="14%" width="14%">

</div>

In [76]:
exam_attempts.loc[:,'attempts'] = exam_attempts.loc[:,'attempts'] .add(1) 
exam_attempts

name  attempts
0  Anastasia         3
1       Andy         5
2  Katherine         4
3      Helen         5
4      Emily         4
5    Michael         5
6    Matthew         3
7      Maria         3
8      Kevin         4
9      Jonas         3

<div class="alert alert-warning">
<b>QUESTION 18:</b>

1, Define a dataframe called `exam_score`:
    
```python
exam_score  = pd.DataFrame({'name': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                            'score': [9., 10., 6.5, np.nan, 8., 8., 5.5, np.nan, 4., 2.]})
```
        
   
2, Merge DataFrames `exam_attempts` and `exam_score` based on the values in column `name`. Assign the merged DataFrame to variable `exam_result`. Display the DataFrame `exam_result`, the expected output would be:

<img src="//i.imgur.com/fur6YEN.png" height="17%" width="17%">
</div>

In [77]:
exam_score  = pd.DataFrame({'name': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                            'score': [9., 10., 6.5, np.nan, 8., 8., 5.5, np.nan, 4., 2.]})
exam_result = pd.merge(exam_attempts, exam_score, on='name', how='outer')
exam_result

name  attempts  score
0  Anastasia         3    9.0
1       Andy         5   10.0
2  Katherine         4    6.5
3      Helen         5    NaN
4      Emily         4    8.0
5    Michael         5    8.0
6    Matthew         3    5.5
7      Maria         3    NaN
8      Kevin         4    4.0
9      Jonas         3    2.0

<div class="alert alert-warning">
<b>QUESTION 19:</b>

For DataFrame `exam_result`, fill the missing values in column `score` with the mean. Display the updated DataFrame, the expected output would be:

<img src="//i.imgur.com/BnbZmI8.png" height="17%" width="17%">
</div>

In [79]:
exam_result['score'] = exam_result['score'].fillna(exam_result['score'].mean())
exam_result

name  attempts   score
0  Anastasia         3   9.000
1       Andy         5  10.000
2  Katherine         4   6.500
3      Helen         5   6.625
4      Emily         4   8.000
5    Michael         5   8.000
6    Matthew         3   5.500
7      Maria         3   6.625
8      Kevin         4   4.000
9      Jonas         3   2.000

<div class="alert alert-warning">
<b>QUESTION 20: </b> 

Display the matching rows in DataFrame `exam_result` where `name` end with `a`, the expected output would be:
    
<img src="//i.imgur.com/mIRWyLs.png" height="20%" width="20%">

</div>

In [80]:
exam_result[exam_result['name'].str.endswith('a')]

name  attempts  score
0  Anastasia         3  9.000
7      Maria         3  6.625